
# --------- Task Start ----------

task-start:
  path: "/task/{task}"
  route: task-start.route.js
  next:
    query: task
    when:
      contact-details: contact-details
      permit-holder-details: permit-holder-details
      site-plan-upload: site-plan-upload
      #      site-name: site-name
      #      confidentiality: confidentiality


# ------------ Tasks -------------

contact-details:
  path: "/contact"
  module: "contact"
  next: task-complete

permit-holder-details:
  path: "/permit-holder"
  module: "contact"
  next: task-complete

<<<<<<< HEAD
site-plan-upload:
  path: "/site-plan-upload"
  module: "upload"
  title: "site-plan-upload title"
  options:
    filetype: "POC demo file"
    title: "Upload a copy of your site plan"
    extensions: ["PNG", "PDF"]
=======
file-upload:
  path: "/upload"
  module: "upload"
  options:
    filetype: "POC demo file"
>>>>>>> 68e0ee2... wip
  next: task-complete

# --------- Task Complete ----------

task-complete:
  path: "/task-complete"
  route: task-complete.route.js

