version: "3.7"
services:
  nginx_test:
    image: "nginx"
    ports:
      - "8000:80"
  web:
    build:
      context: ${PWD}/poc_front_end
      dockerfile: ${PWD}/poc_front_end/dev.Dockerfile
    ports:
      - "80:3000"
    volumes:
      # overlay local file system and mount in container
      - ${PWD}/poc_front_end/bin:/home/node/bin
      - ${PWD}/poc_front_end/src:/home/node/src
      # use a volume to persist node_modules, prevents leakage to host
      - web_node_modules:/home/node/node_modules
    environment:
      HOST_NAME: "web"
    entrypoint: "/home/node/bin/run_watch.sh"
  unit.test:
    build:
      context: ${PWD}/poc_front_end
      dockerfile: ${PWD}/poc_front_end/dev.Dockerfile
    ports:
      - "8080:3000"
    volumes:
      # overlay local file system and mount in container
      - ${PWD}/poc_front_end/bin:/home/node/bin
      - ${PWD}/poc_front_end/src:/home/node/src
      - ${PWD}/poc_front_end/test:/home/node/test
      # use a volume to persist node_modules, prevents leakage to host
      - unit_test_node_modules:/home/node/node_modules
    environment:
      HOST_NAME: "unit.test"
    entrypoint: /home/node/bin/run_watch_test.sh
volumes:
  web_node_modules: {}
  unit_test_node_modules: {}
