version: "3.7"
services:
  nginx_test:
    image: "nginx"
    ports:
      - "8000:80"
  web:
    image: poc_front_end
    ports:
      - "80:3000"
    environment:
      HOST_NAME: "web"
  unit.test:
    image: poc_front_end
    ports:
      - "8080:3000"
    environment:
      HOST_NAME: "unit.test"
volumes:
  web_node_modules: {}
  unit_test_node_modules: {}

